# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runGibbs <- function(inData, dataMeans, dataScales, nTargets, lambda1Starts, lambda2Starts, sigmaStarts, tauStarts, betaStarts, missCode, nEmApproxIters, nEmTuneIters, emApprox_nBurnIns, emApprox_gibbsSampleSize, emTune_nBurnIns, emTune_gibbsSampleSize, posteriorGibbs_nBurnIns, posteriorGibbs_gibbsSampleSize, lambdaWindow, emConvTol, verboseIters, verboseErrors, doMibl) {
    .Call('mibrr_runGibbs', PACKAGE = 'mibrr', inData, dataMeans, dataScales, nTargets, lambda1Starts, lambda2Starts, sigmaStarts, tauStarts, betaStarts, missCode, nEmApproxIters, nEmTuneIters, emApprox_nBurnIns, emApprox_gibbsSampleSize, emTune_nBurnIns, emTune_gibbsSampleSize, posteriorGibbs_nBurnIns, posteriorGibbs_gibbsSampleSize, lambdaWindow, emConvTol, verboseIters, verboseErrors, doMibl)
}

