# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drawInvGamma <- function(n, shape, scale) {
    .Call('mibrr_drawInvGamma', PACKAGE = 'mibrr', n, shape, scale)
}

drawMVN <- function(n, meanVec, covMat) {
    .Call('mibrr_drawMVN', PACKAGE = 'mibrr', n, meanVec, covMat)
}

calcIncGamma <- function(shape, cutVal, lowerTail) {
    .Call('mibrr_calcIncGamma', PACKAGE = 'mibrr', shape, cutVal, lowerTail)
}

drawInvGauss <- function(n, mu, lambda) {
    .Call('mibrr_drawInvGauss', PACKAGE = 'mibrr', n, mu, lambda)
}

runGibbs <- function(inData, dataScales, nTargets, missList, respCounts, lambda1Starts, lambda2Starts, sigmaStarts, tauStarts, betaStarts, nApproxIters, nTuneIters, nApproxBurn, nApproxGibbs, nTuneBurn, nTuneGibbs, nPostBurn, nPostGibbs, lambdaWindow, emConvTol, verbose, doBl, doImputation, adaptScales, simpleIntercept, twoPhaseOpt) {
    .Call('mibrr_runGibbs', PACKAGE = 'mibrr', inData, dataScales, nTargets, missList, respCounts, lambda1Starts, lambda2Starts, sigmaStarts, tauStarts, betaStarts, nApproxIters, nTuneIters, nApproxBurn, nApproxGibbs, nTuneBurn, nTuneGibbs, nPostBurn, nPostGibbs, lambdaWindow, emConvTol, verbose, doBl, doImputation, adaptScales, simpleIntercept, twoPhaseOpt)
}

