# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runGibbs <- function(data, nTargets, missList, respCounts, lambda1, lambda2, l1Parms, l2Parms, sigmaStarts, tauStarts, betaStarts, burnSams, totalSams, penType, ridge, verbose, fullBayes, noMiss, savePpSams, seeds) {
    .Call('_MIBRR_runGibbs', PACKAGE = 'MIBRR', data, nTargets, missList, respCounts, lambda1, lambda2, l1Parms, l2Parms, sigmaStarts, tauStarts, betaStarts, burnSams, totalSams, penType, ridge, verbose, fullBayes, noMiss, savePpSams, seeds)
}

drawNorm <- function(n, mean, sd, seed) {
    .Call('_MIBRR_drawNorm', PACKAGE = 'MIBRR', n, mean, sd, seed)
}

drawGamma <- function(n, shape, rate, seed) {
    .Call('_MIBRR_drawGamma', PACKAGE = 'MIBRR', n, shape, rate, seed)
}

drawInvGamma <- function(n, shape, scale, seed) {
    .Call('_MIBRR_drawInvGamma', PACKAGE = 'MIBRR', n, shape, scale, seed)
}

drawScaledInvChiSq <- function(n, df, scale, seed) {
    .Call('_MIBRR_drawScaledInvChiSq', PACKAGE = 'MIBRR', n, df, scale, seed)
}

drawMvn <- function(n, meanVec, covMat, seed) {
    .Call('_MIBRR_drawMvn', PACKAGE = 'MIBRR', n, meanVec, covMat, seed)
}

calcIncGamma <- function(shape, cutVal, lowerTail) {
    .Call('_MIBRR_calcIncGamma', PACKAGE = 'MIBRR', shape, cutVal, lowerTail)
}

drawInvGauss <- function(n, mu, lambda, seed) {
    .Call('_MIBRR_drawInvGauss', PACKAGE = 'MIBRR', n, mu, lambda, seed)
}

drawGig <- function(n, lambda, chi, psi, seed) {
    .Call('_MIBRR_drawGig', PACKAGE = 'MIBRR', n, lambda, chi, psi, seed)
}

printObsIndices <- function(data, missIndices, respCounts, targetIndex) {
    .Call('_MIBRR_printObsIndices', PACKAGE = 'MIBRR', data, missIndices, respCounts, targetIndex)
}

printMissIndices <- function(data, missIndices, respCounts, targetIndex) {
    .Call('_MIBRR_printMissIndices', PACKAGE = 'MIBRR', data, missIndices, respCounts, targetIndex)
}

getX <- function(data, missIndices, respCounts, noMiss, xOnly, obsY, scale, targetIndex) {
    .Call('_MIBRR_getX', PACKAGE = 'MIBRR', data, missIndices, respCounts, noMiss, xOnly, obsY, scale, targetIndex)
}

getY <- function(data, missIndices, respCounts, noMiss, targetIndex) {
    .Call('_MIBRR_getY', PACKAGE = 'MIBRR', data, missIndices, respCounts, noMiss, targetIndex)
}

printFilledY <- function(imps, data, missIndices, respCounts, targetIndex) {
    .Call('_MIBRR_printFilledY', PACKAGE = 'MIBRR', imps, data, missIndices, respCounts, targetIndex)
}

